"""
Comprehensive list of tickers organized by stock index.
Sources: CAC 40, S&P 500 (top 50), EuroStoxx 50, SBF 120 extra
"""

CAC40 = [
    {"ticker": "AI.PA", "name": "Air Liquide", "index_name": "CAC 40", "sector": "Materials"},
    {"ticker": "AIR.PA", "name": "Airbus", "index_name": "CAC 40", "sector": "Industrials"},
    {"ticker": "ALO.PA", "name": "Alstom", "index_name": "CAC 40", "sector": "Industrials"},
    {"ticker": "MT.AS", "name": "ArcelorMittal", "index_name": "CAC 40", "sector": "Materials"},
    {"ticker": "CS.PA", "name": "AXA", "index_name": "CAC 40", "sector": "Financials"},
    {"ticker": "BNP.PA", "name": "BNP Paribas", "index_name": "CAC 40", "sector": "Financials"},
    {"ticker": "EN.PA", "name": "Bouygues", "index_name": "CAC 40", "sector": "Communication"},
    {"ticker": "CAP.PA", "name": "Capgemini", "index_name": "CAC 40", "sector": "Technology"},
    {"ticker": "CA.PA", "name": "Carrefour", "index_name": "CAC 40", "sector": "Consumer"},
    {"ticker": "ACA.PA", "name": "Crédit Agricole", "index_name": "CAC 40", "sector": "Financials"},
    {"ticker": "BN.PA", "name": "Danone", "index_name": "CAC 40", "sector": "Consumer"},
    {"ticker": "DSY.PA", "name": "Dassault Systèmes", "index_name": "CAC 40", "sector": "Technology"},
    {"ticker": "EL.PA", "name": "EssilorLuxottica", "index_name": "CAC 40", "sector": "Healthcare"},
    {"ticker": "ERF.PA", "name": "Eurofins Scientific", "index_name": "CAC 40", "sector": "Healthcare"},
    {"ticker": "RMS.PA", "name": "Hermès International", "index_name": "CAC 40", "sector": "Consumer"},
    {"ticker": "KER.PA", "name": "Kering", "index_name": "CAC 40", "sector": "Consumer"},
    {"ticker": "LR.PA", "name": "Legrand", "index_name": "CAC 40", "sector": "Industrials"},
    {"ticker": "OR.PA", "name": "L'Oréal", "index_name": "CAC 40", "sector": "Consumer"},
    {"ticker": "MC.PA", "name": "LVMH", "index_name": "CAC 40", "sector": "Consumer"},
    {"ticker": "ML.PA", "name": "Michelin", "index_name": "CAC 40", "sector": "Consumer"},
    {"ticker": "ORA.PA", "name": "Orange", "index_name": "CAC 40", "sector": "Communication"},
    {"ticker": "RI.PA", "name": "Pernod Ricard", "index_name": "CAC 40", "sector": "Consumer"},
    {"ticker": "PUB.PA", "name": "Publicis Groupe", "index_name": "CAC 40", "sector": "Communication"},
    {"ticker": "RNO.PA", "name": "Renault", "index_name": "CAC 40", "sector": "Consumer"},
    {"ticker": "SAF.PA", "name": "Safran", "index_name": "CAC 40", "sector": "Industrials"},
    {"ticker": "SAN.PA", "name": "Sanofi", "index_name": "CAC 40", "sector": "Healthcare"},
    {"ticker": "SGO.PA", "name": "Saint-Gobain", "index_name": "CAC 40", "sector": "Industrials"},
    {"ticker": "SU.PA", "name": "Schneider Electric", "index_name": "CAC 40", "sector": "Industrials"},
    {"ticker": "GLE.PA", "name": "Société Générale", "index_name": "CAC 40", "sector": "Financials"},
    {"ticker": "STMPA.PA", "name": "STMicroelectronics", "index_name": "CAC 40", "sector": "Technology"},
    {"ticker": "TEP.PA", "name": "Teleperformance", "index_name": "CAC 40", "sector": "Industrials"},
    {"ticker": "HO.PA", "name": "Thales", "index_name": "CAC 40", "sector": "Industrials"},
    {"ticker": "TTE.PA", "name": "TotalEnergies", "index_name": "CAC 40", "sector": "Energy"},
    {"ticker": "URW.AS", "name": "Unibail-Rodamco-Westfield", "index_name": "CAC 40", "sector": "Real Estate"},
    {"ticker": "VIE.PA", "name": "Veolia Environnement", "index_name": "CAC 40", "sector": "Utilities"},
    {"ticker": "DG.PA", "name": "Vinci", "index_name": "CAC 40", "sector": "Industrials"},
    {"ticker": "VIV.PA", "name": "Vivendi", "index_name": "CAC 40", "sector": "Communication"},
    {"ticker": "WLN.PA", "name": "Worldline", "index_name": "CAC 40", "sector": "Technology"},
    {"ticker": "STLA.AS", "name": "Stellantis", "index_name": "CAC 40", "sector": "Consumer"},
    {"ticker": "AMUN.PA", "name": "Amundi", "index_name": "CAC 40", "sector": "Financials"},
]

SP500 = [
    {"ticker": "AAPL", "name": "Apple", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "MSFT", "name": "Microsoft", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "NVDA", "name": "NVIDIA", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "AMZN", "name": "Amazon", "index_name": "S&P 500", "sector": "Consumer"},
    {"ticker": "GOOGL", "name": "Alphabet (Google)", "index_name": "S&P 500", "sector": "Communication"},
    {"ticker": "META", "name": "Meta Platforms", "index_name": "S&P 500", "sector": "Communication"},
    {"ticker": "TSLA", "name": "Tesla", "index_name": "S&P 500", "sector": "Consumer"},
    {"ticker": "BRK-B", "name": "Berkshire Hathaway", "index_name": "S&P 500", "sector": "Financials"},
    {"ticker": "JPM", "name": "JPMorgan Chase", "index_name": "S&P 500", "sector": "Financials"},
    {"ticker": "JNJ", "name": "Johnson & Johnson", "index_name": "S&P 500", "sector": "Healthcare"},
    {"ticker": "V", "name": "Visa", "index_name": "S&P 500", "sector": "Financials"},
    {"ticker": "PG", "name": "Procter & Gamble", "index_name": "S&P 500", "sector": "Consumer"},
    {"ticker": "UNH", "name": "UnitedHealth Group", "index_name": "S&P 500", "sector": "Healthcare"},
    {"ticker": "HD", "name": "Home Depot", "index_name": "S&P 500", "sector": "Consumer"},
    {"ticker": "MA", "name": "Mastercard", "index_name": "S&P 500", "sector": "Financials"},
    {"ticker": "BAC", "name": "Bank of America", "index_name": "S&P 500", "sector": "Financials"},
    {"ticker": "XOM", "name": "ExxonMobil", "index_name": "S&P 500", "sector": "Energy"},
    {"ticker": "ABBV", "name": "AbbVie", "index_name": "S&P 500", "sector": "Healthcare"},
    {"ticker": "CVX", "name": "Chevron", "index_name": "S&P 500", "sector": "Energy"},
    {"ticker": "KO", "name": "Coca-Cola", "index_name": "S&P 500", "sector": "Consumer"},
    {"ticker": "PEP", "name": "PepsiCo", "index_name": "S&P 500", "sector": "Consumer"},
    {"ticker": "MRK", "name": "Merck", "index_name": "S&P 500", "sector": "Healthcare"},
    {"ticker": "AVGO", "name": "Broadcom", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "TMO", "name": "Thermo Fisher Scientific", "index_name": "S&P 500", "sector": "Healthcare"},
    {"ticker": "COST", "name": "Costco Wholesale", "index_name": "S&P 500", "sector": "Consumer"},
    {"ticker": "DIS", "name": "Walt Disney", "index_name": "S&P 500", "sector": "Communication"},
    {"ticker": "ABT", "name": "Abbott Laboratories", "index_name": "S&P 500", "sector": "Healthcare"},
    {"ticker": "ACN", "name": "Accenture", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "CSCO", "name": "Cisco Systems", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "ADBE", "name": "Adobe", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "CRM", "name": "Salesforce", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "NKE", "name": "Nike", "index_name": "S&P 500", "sector": "Consumer"},
    {"ticker": "LLY", "name": "Eli Lilly", "index_name": "S&P 500", "sector": "Healthcare"},
    {"ticker": "AMD", "name": "Advanced Micro Devices", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "QCOM", "name": "Qualcomm", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "TXN", "name": "Texas Instruments", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "HON", "name": "Honeywell International", "index_name": "S&P 500", "sector": "Industrials"},
    {"ticker": "INTC", "name": "Intel", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "INTU", "name": "Intuit", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "GS", "name": "Goldman Sachs", "index_name": "S&P 500", "sector": "Financials"},
    {"ticker": "MS", "name": "Morgan Stanley", "index_name": "S&P 500", "sector": "Financials"},
    {"ticker": "CAT", "name": "Caterpillar", "index_name": "S&P 500", "sector": "Industrials"},
    {"ticker": "IBM", "name": "IBM", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "GE", "name": "General Electric", "index_name": "S&P 500", "sector": "Industrials"},
    {"ticker": "WMT", "name": "Walmart", "index_name": "S&P 500", "sector": "Consumer"},
    {"ticker": "PFE", "name": "Pfizer", "index_name": "S&P 500", "sector": "Healthcare"},
    {"ticker": "ORCL", "name": "Oracle", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "NOW", "name": "ServiceNow", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "UBER", "name": "Uber Technologies", "index_name": "S&P 500", "sector": "Technology"},
    {"ticker": "NFLX", "name": "Netflix", "index_name": "S&P 500", "sector": "Communication"},
    {"ticker": "PYPL", "name": "PayPal", "index_name": "S&P 500", "sector": "Financials"},
]

EUROSTOXX50 = [
    {"ticker": "ASML.AS", "name": "ASML Holding", "index_name": "EuroStoxx 50", "sector": "Technology"},
    {"ticker": "SAP.DE", "name": "SAP", "index_name": "EuroStoxx 50", "sector": "Technology"},
    {"ticker": "SIE.DE", "name": "Siemens", "index_name": "EuroStoxx 50", "sector": "Industrials"},
    {"ticker": "ALV.DE", "name": "Allianz", "index_name": "EuroStoxx 50", "sector": "Financials"},
    {"ticker": "MUV2.DE", "name": "Munich Re", "index_name": "EuroStoxx 50", "sector": "Financials"},
    {"ticker": "BMW.DE", "name": "BMW", "index_name": "EuroStoxx 50", "sector": "Consumer"},
    {"ticker": "BAS.DE", "name": "BASF", "index_name": "EuroStoxx 50", "sector": "Materials"},
    {"ticker": "BAYN.DE", "name": "Bayer", "index_name": "EuroStoxx 50", "sector": "Healthcare"},
    {"ticker": "DTE.DE", "name": "Deutsche Telekom", "index_name": "EuroStoxx 50", "sector": "Communication"},
    {"ticker": "DB1.DE", "name": "Deutsche Börse", "index_name": "EuroStoxx 50", "sector": "Financials"},
    {"ticker": "IFX.DE", "name": "Infineon Technologies", "index_name": "EuroStoxx 50", "sector": "Technology"},
    {"ticker": "VOW3.DE", "name": "Volkswagen", "index_name": "EuroStoxx 50", "sector": "Consumer"},
    {"ticker": "FRE.DE", "name": "Fresenius", "index_name": "EuroStoxx 50", "sector": "Healthcare"},
    {"ticker": "NOKIA.HE", "name": "Nokia", "index_name": "EuroStoxx 50", "sector": "Technology"},
    {"ticker": "ITX.MC", "name": "Inditex (Zara)", "index_name": "EuroStoxx 50", "sector": "Consumer"},
    {"ticker": "IBE.MC", "name": "Iberdrola", "index_name": "EuroStoxx 50", "sector": "Utilities"},
    {"ticker": "SAN.MC", "name": "Banco Santander", "index_name": "EuroStoxx 50", "sector": "Financials"},
    {"ticker": "BBVA.MC", "name": "BBVA", "index_name": "EuroStoxx 50", "sector": "Financials"},
    {"ticker": "REP.MC", "name": "Repsol", "index_name": "EuroStoxx 50", "sector": "Energy"},
    {"ticker": "ENEL.MI", "name": "Enel", "index_name": "EuroStoxx 50", "sector": "Utilities"},
    {"ticker": "ENI.MI", "name": "ENI", "index_name": "EuroStoxx 50", "sector": "Energy"},
    {"ticker": "ISP.MI", "name": "Intesa Sanpaolo", "index_name": "EuroStoxx 50", "sector": "Financials"},
    {"ticker": "STLA.MI", "name": "Stellantis", "index_name": "EuroStoxx 50", "sector": "Consumer"},
    {"ticker": "ADYEN.AS", "name": "Adyen", "index_name": "EuroStoxx 50", "sector": "Technology"},
    {"ticker": "INGA.AS", "name": "ING Groep", "index_name": "EuroStoxx 50", "sector": "Financials"},
    {"ticker": "PHIA.AS", "name": "Philips", "index_name": "EuroStoxx 50", "sector": "Healthcare"},
    {"ticker": "PRX.AS", "name": "Prosus", "index_name": "EuroStoxx 50", "sector": "Technology"},
    {"ticker": "AD.AS", "name": "Ahold Delhaize", "index_name": "EuroStoxx 50", "sector": "Consumer"},
]

SBF120_EXTRA = [
    {"ticker": "AC.PA", "name": "Accor", "index_name": "SBF 120", "sector": "Consumer"},
    {"ticker": "AKE.PA", "name": "Arkema", "index_name": "SBF 120", "sector": "Materials"},
    {"ticker": "BIM.PA", "name": "bioMérieux", "index_name": "SBF 120", "sector": "Healthcare"},
    {"ticker": "BVI.PA", "name": "Bureau Veritas", "index_name": "SBF 120", "sector": "Industrials"},
    {"ticker": "COV.PA", "name": "Covivio", "index_name": "SBF 120", "sector": "Real Estate"},
    {"ticker": "FGR.PA", "name": "Eiffage", "index_name": "SBF 120", "sector": "Industrials"},
    {"ticker": "RF.PA", "name": "Eurazeo", "index_name": "SBF 120", "sector": "Financials"},
    {"ticker": "IPN.PA", "name": "Ipsen", "index_name": "SBF 120", "sector": "Healthcare"},
    {"ticker": "LI.PA", "name": "Klépierre", "index_name": "SBF 120", "sector": "Real Estate"},
    {"ticker": "NEX.PA", "name": "Nexans", "index_name": "SBF 120", "sector": "Industrials"},
    {"ticker": "RXL.PA", "name": "Rexel", "index_name": "SBF 120", "sector": "Industrials"},
    {"ticker": "SOP.PA", "name": "Sopra Steria", "index_name": "SBF 120", "sector": "Technology"},
    {"ticker": "TRI.PA", "name": "Trigano", "index_name": "SBF 120", "sector": "Consumer"},
    {"ticker": "FR.PA", "name": "Valeo", "index_name": "SBF 120", "sector": "Consumer"},
    {"ticker": "VCT.PA", "name": "Vicat", "index_name": "SBF 120", "sector": "Materials"},
    {"ticker": "TFII.TO", "name": "TFI International", "index_name": "SBF 120", "sector": "Industrials"},
    {"ticker": "GTT.PA", "name": "GTT", "index_name": "SBF 120", "sector": "Industrials"},
    {"ticker": "EXAI.PA", "name": "Exacompta Clairefontaine", "index_name": "SBF 120", "sector": "Industrials"},
    {"ticker": "ALTU.PA", "name": "Altus Intervention", "index_name": "SBF 120", "sector": "Energy"},
    {"ticker": "OPT.PA", "name": "OPmobility", "index_name": "SBF 120", "sector": "Consumer"},
]

# Merge all
ALL_TICKERS = CAC40 + SP500 + EUROSTOXX50 + SBF120_EXTRA

INDICES = {
    "CAC 40": CAC40,
    "S&P 500": SP500,
    "EuroStoxx 50": EUROSTOXX50,
    "SBF 120": SBF120_EXTRA,
}
